# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(CIRRUS_TOP)/include

cirrus_irq-madera-objs = irq-madera.o

obj-y += cirrus_irq-madera.o

cirrus_irq-tacna-objs = irq-tacna.o

obj-y += cirrus_irq-tacna.o
