# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(CIRRUS_TOP)/vendor/cirrus/audio/dlkm/include
EXTRA_CFLAGS += -DCONFIG_EXTCON_MADERA_INPUT_EVENT
EXTRA_CFLAGS += -DCONFIG_EXTCON_TACNA_INPUT_EVENT

obj-y += extcon-madera.o

obj-y += extcon-tacna.o
